### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by aljowen** [marc-hanheide/QuickVote#11]
When trying to submit an answer i am taken to a page that states internal server error regardless of whether i have answered the question before or not. Clearing cookies for quickvote does not fix the issue.
![quickvote](https://cloud.githubusercontent.com/assets/16223353/11684258/50b016d2-9e68-11e5-8f83-7b29f59f6a62.png)
![quickvote2](https://cloud.githubusercontent.com/assets/16223353/11684314/afa408c4-9e68-11e5-859e-2a9eb398385f.png)

**Comment by marc-hanheide** [comment]
Hmm... odd. Thanks for reporting it. So far I have been unable to reproduce it... I need to check further.

**Comment by TGRHavoc** [comment]
If you look at the second image aljowen seems to be ending up at /api/api.

Could be "submit_url" not being the correct value for some reason.

**Comment by aljowen** [comment]
I have found in grzegorz's lectures that I can get it to start working again by modifying the api section of the url. But if it breaks in this way it will usually state that I have already answered the new question when I haven't.
The same issue has also been happening on some of my friends Android devices too.

**Comment by marc-hanheide** [comment]
Ah, so it's a problem with the reverse proxy... that's a good hint, well spotted. I'll check.
