### ISSUE TITLE
View and empty session

### ISSUE THREAD

**Issue by gcielniak** [marc-hanheide/QuickVote#12]
Currently when there are no question specified in the editor, the viewer returns error.

**Comment by marc-hanheide** [comment]
Not sure I understand... What do you mean precisely?

**Comment by gcielniak** [comment]
In a scenario where there is an empty session without any questions in the editor, if you run the viewer you get an error reported. To replicate: remove all questions and run the student view.

**Comment by marc-hanheide** [comment]
So, it's only when there are now questions at all? Right, then the "active question" becomes in valid. This will likely even happen if you delete the question that is currently active in the "/view" in the editor. I think in general, we need a better exception handling. The user shouldn't just see a server error, but some useful information instead...

**Comment by marc-hanheide** [comment]
I hopefully fixed this in e7ac46fc13116f0368a80395c52a8022863894aa
