### ISSUE TITLE
Editor - droplist showing the first added item 

### ISSUE THREAD

**Issue by gcielniak** [marc-hanheide/QuickVote#13]
This more like an enhancement request than a real error. When I create a new question then the drop list still shows the first created question. Perhaps if that was showing New instead it would be more intuitive?

**Comment by marc-hanheide** [comment]
It shows the currently active question (the one selected in the view), based on the idea that you might want to edit the active question most urgently. I can see where you are coming from, but not sure that is the best way either...

**Comment by gcielniak** [comment]
A fair point, it is not a biggy anyway...

**Comment by marc-hanheide** [comment]
I'll close for now, as I don't plan to fix it yet. I might think of better ways for future releases though.
