### ISSUE TITLE
Roles and Domains

### ISSUE THREAD

**Issue by marc-hanheide** [marc-hanheide/QuickVote#21]
# Roles:

User need to be assign to roles in domains:
- admin (can do everything)
- coordinator (can assign users and edit everything in specific domains)
- editor (can edit questions within specific domains, but cannot change user roles/domains)
# Actions:

| action | roles |
| --- | --- |
| create/modify/delete users (only needed for database authentication backend) | admin |
| modify roles of users | admin |
| create/modify/delete domains | admin |
| enrol/unenrol new users to domain | admin, coordinator |
| create/modify/delete questions | admin, coordinator, editor |
- [x] interface to assign roles
- [x] interface to edit domains
- [x] interface to enrol/unenrol users to domains

**Comment by 13465012** [comment]
Also being implemented in #25 but still in the experimental phase (no built in interface yet)

**Comment by 13465012** [comment]
Domain user permissions being changed from child object in mongodb to nested lists in order to enable querying of users by permission as well as permission by users.

**Comment by marc-hanheide** [comment]
> Domain user permissions being changed from child object in mongodb to nested lists in order to enable querying of users by permission as well as permission by users.

Not sure I understand that, can you paste an example document of how it's structure now, @13465012?

**Comment by 13465012** [comment]
Previously as a child object:
`"users" : {
        "Admin" : "Admin",
        "Coord" : "Coord"
    },`
Now as nested lists:
`"users" : [ 
        [ "Admin", "Admin" ], 
        [ "Coord", "Coord" ]
    ]`
