### ISSUE TITLE
entry page

### ISSUE THREAD

**Issue by marc-hanheide** [marc-hanheide/QuickVote#23]
There is no entry page at the moment. There should be one listing the following:
- [x] login
- [x] link to github page and documentation
- [x] List of domains (sorted according to last active time, last active displayed first)

**Comment by marc-hanheide** [comment]
also included in #25 but so far not sorting domains according to access time.

**Comment by 13465012** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14558276/16727420/e3005896-4758-11e6-854c-2680014120ac.png)

**Comment by marc-hanheide** [comment]
@13465012 well done!

**Comment by 13465012** [comment]
Domains listed by most recently active now. Information on domains shown to users who are not logged in on landing page is complete. Logged in users still needs finishing.
![capture](https://cloud.githubusercontent.com/assets/14558276/16776053/6f27722a-485b-11e6-98cf-5b4838eace72.PNG)

**Comment by marc-hanheide** [comment]
Brilliant. Well done. I hope to be able to test all this on Thursday.

**Comment by marc-hanheide** [comment]
add a "help" button, that links either to [User's Guide](https://github.com/marc-hanheide/QuickVote/wiki/User's-Guide) or the [Admin's Guide](https://github.com/marc-hanheide/QuickVote/wiki/Admin's-Guide)
