### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by marc-hanheide** [marc-hanheide/QuickVote#27]
To make the code more legible and manageable, we shall restructure and refactor a bit
- [x] remove dead code
- [x] refactor all Page classes (the ones that directly serve sites via `GET` or `PUSH` into one file
- [x] refactor the "logic" classes (such as domain management etc) into its own file etc...
- [x] keep one main `app.py` with just the core logic (`main()` and the import and config reading)

**Comment by 13465012** [comment]
Refactoring complete in 13465012@34bd64c3915e7efe077ffac56d869411829519ad and dead code removed in 13465012@926e80da26302397747bb47f8ef01704abe5a551
