### ISSUE TITLE
QuickVote not working with PyMongo >3.0 in Apache

### ISSUE THREAD

**Issue by marc-hanheide** [marc-hanheide/QuickVote#36]
I get this:

```
[Tue Aug 09 16:37:00.009080 2016] [:error] [pid 691] [remote 79.236.204.130:39251] mod_wsgi (pid=691): Exception occurred processing WSGI script '/var/www/QuickVote/app.py'.
[Tue Aug 09 16:37:00.009170 2016] [:error] [pid 691] [remote 79.236.204.130:39251] Traceback (most recent call last):
[Tue Aug 09 16:37:00.009218 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/var/www/QuickVote/app.py", line 11, in <module>
[Tue Aug 09 16:37:00.009300 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     from modules.common import *
[Tue Aug 09 16:37:00.009315 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/var/www/QuickVote/modules/common.py", line 33, in <module>
[Tue Aug 09 16:37:00.009348 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     qv_collection.create_index('uuid')
[Tue Aug 09 16:37:00.009360 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1387, in create_index
[Tue Aug 09 16:37:00.009680 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     self.__create_index(keys, kwargs)
[Tue Aug 09 16:37:00.009691 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1294, in __create_index
[Tue Aug 09 16:37:00.009713 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     with self._socket_for_writes() as sock_info:
[Tue Aug 09 16:37:00.009723 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
[Tue Aug 09 16:37:00.009765 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     return self.gen.next()
[Tue Aug 09 16:37:00.009774 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 762, in _get_socket
[Tue Aug 09 16:37:00.009984 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     server = self._get_topology().select_server(selector)
[Tue Aug 09 16:37:00.009999 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 210, in select_server
[Tue Aug 09 16:37:00.010394 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     address))
[Tue Aug 09 16:37:00.010406 2016] [:error] [pid 691] [remote 79.236.204.130:39251]   File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 186, in select_servers
[Tue Aug 09 16:37:00.010419 2016] [:error] [pid 691] [remote 79.236.204.130:39251]     self._error_message(selector))
[Tue Aug 09 16:37:00.010432 2016] [:error] [pid 691] [remote 79.236.204.130:39251] ServerSelectionTimeoutError: No servers found yet
```

This is also reported in other places, like:
- http://stackoverflow.com/questions/31030307/why-is-pymongo-3-giving-serverselectiontimeouterror/31194981#31194981 
- https://github.com/dcrosta/flask-pymongo/pull/67

The problem stems from the new QV's requirement of using PyMongo >3.0 (which in principle is good!), but it seems the new verison of PyMongo has a problem (at least with the "old" MongoDB server (2.0.4) we are trying to connect to). This needs investigation, as currently QuickVote cannot run on the server due to this issue.

Assigning to @13465012 for consultation.

**Comment by 13465012** [comment]
I see, I will have to install MongoDB 2.0.4 and then look for a solution

**Comment by 13465012** [comment]
2.0.4 or 2.4.0? their [win32 downloads](https://www.mongodb.org/dl/win32/x86_64-2008plus-ssl) don't go back as far as 2.0

**Comment by marc-hanheide** [comment]
We still use 2.0.4, but that doesn't appear to be the problem. It's some PyMongo >3.0 bug it seems which only shows when running in WSGI, ie in a web server, not when running stand-alone. Some nasty race condition in multi-threaded environments. Hard to reproduce, but I always get it in the server environment. I can't give you access to it ATM, I'm afraid, though.

**Comment by 13465012** [comment]
I see, i'm not sure what i can do towards fixing it then besides spending some time looking for solutions other's might have found only though

**Comment by marc-hanheide** [comment]
yeah... I did a bit of research myself and all I tried didn't yield a solution yet. Only suggestions were to downgrade back to PyMongo 2.8 as people considered 3.0 not mature enough. But that would mean many API changes (I upgrade to PyMongo 3.0 locally as I noticed you used the new API). This is obviously normally good... but in this case the last resort will be to revert back to 2.8...

**Comment by 13465012** [comment]
I see, i'm guessing you can update the server's MongoDB?

**Comment by marc-hanheide** [comment]
that server update won't help... or at least it's very unlikely, right? It's a PyMongo issue, not a server issue from all I gathered so far.

**Comment by 13465012** [comment]
I see, i just wondered if it could be an incompatibility issue

**Comment by marc-hanheide** [comment]
maybe, but no post I found hints that direction. I can't easily update this in the production system at the moment...

**Comment by 13465012** [comment]
ok, we'll have to rule out everything else first then

**Comment by 13465012** [comment]
have you tried [this](http://stackoverflow.com/a/31854139)?

**Comment by marc-hanheide** [comment]
yep, obviously ;-) but didn't help...

**Comment by 13465012** [comment]
We might have to revert back to 2.8, i can't find anything about fixing this issue. It'll be a pain in the neck though
